# mlbv: I moved most settings that require a cache invalidation to buildscript.properties.
# this file is no longer hashed for GitHub Actions.

# Version of your mod.
# This field can be left empty if you want your mod's version to be determined by the latest git tag instead.
# mlbv: our naming convention is MAJORMOD.MAJORAPI.MINOR.PATCH per forge's recommendation.

modVersion = 2.2.0


# Gradle Settings
# Effectively applies the '--stacktrace' flag by default
org.gradle.logging.stacktrace = all
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.vfs.watch = true

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs = -Xmx6G

# Increase HTTP timeout and retry windows for large artifact transfers during dependency resolution and publishing.
systemProp.org.gradle.internal.http.connectionTimeout = 150000
systemProp.org.gradle.internal.http.socketTimeout = 600000
systemProp.org.gradle.internal.http.idleConnectionTimeout = 180000
systemProp.org.gradle.internal.network.retry.max.attempts = 5
systemProp.org.gradle.internal.network.retry.initial.backOff = 2000

# Additional arguments applied to the JVM when launching minecraft
# Syntax: -arg1=value1;-arg2=value2;...
# Example value: -Dmixin.debug.verify=true;-XX:+UnlockExperimentalVMOptions
# Append these to test netty native leak(would degrade performance): -Dio.netty.leakDetection.level=paranoid;-Dio.netty.leakDetection.maxRecords=10;
additionalJavaArguments = -Xmx16G;-XX:+UseG1GC;-XX:+UseLargePages;-Dfile.encoding=UTF-8;-Dforge.verboseMissingModelLoggingCount=1000000;-Dorg.lwjgl.util.Debug=true
